---
# tasks file for vagrant
- when: ansible_os_family == "Debian"
  block:
    - name: download vagrant package
      get_url:
        url: "{{ vagrant_download_url }}.deb"
        dest: /tmp
      changed_when: false

    - name: Install vagrant
      command: dpkg -i "/tmp/{{ vagrant_package_name }}.deb"
      changed_when: false


- when: ansible_os_family == "Centos"
  block:
    - name: Download vagrant package
      get_url:
        url: "{{ vagrant_download_url }}.rpm"
        dest: /tmp
      changed_when: false

    - name: Install vagrant
      command: yum install -y "/tmp/{{ vagrant_package_name }}.rpm"
      changed_when: false

- when: ansible_os_family == "Fedora"
  block:
    - name: Download vagrant package
      get_url:
        url: "{{ vagrant_download_url }}.rpm"
        dest: /tmp
      changed_when: false

    - name: Install vagrant
      command: yum install -y "/tmp/{{ vagrant_package_name }}.rpm"
      changed_when: false
